### ISSUE TITLE
npm i -g wey gives "compiled against a different Node.js version using" error

### ISSUE THREAD

**Issue by idchlife** [yue/wey#1]
Here is the full error:

```javascript
module.js:672
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '/Users/igorandreev/.nvm/versions/node/v9.2.0/lib/node_modules/wey/node_modules/gui/gui.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:672:18)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/igorandreev/.nvm/versions/node/v9.2.0/lib/node_modules/wey/node_modules/gui/index.js:4:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
```

**Comment by zcbenz** [comment]
Currently you can only use Node 8.x for installing Wey, I will try to find a way to fix this.
