### ISSUE TITLE
Mention node version required in README

### ISSUE THREAD

**Issue by wjdp** [yue/wey#16]
```
~ ❯ uname -a                                                                                                                        ↩
Linux PF0PUTTL 4.13.0-38-generic #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
~ ❯ node --version                                                                                                                  ↩
v6.14.1
~ ❯ npm version
{ npm: '5.8.0',
  ares: '1.10.1-DEV',
  http_parser: '2.8.0',
  icu: '58.2',
  modules: '48',
  node: '6.14.1',
  openssl: '1.0.2o',
  uv: '1.16.1',
  v8: '5.1.281.111',
  zlib: '1.2.11' }
~ ❯ sudo npm install -g wey
/usr/bin/wey -> /usr/lib/node_modules/wey/scripts/start.js

> keytar@4.2.1 install /usr/lib/node_modules/wey/node_modules/keytar
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/keytar-v4.2.1-node-v48-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /home/will/.npm/_prebuilds/https-github.com-atom-node-keytar-releases-download-v4.2.1-keytar-v4.2.1-node-v48-linux-x64.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ /home/will/.npm/_prebuilds/https-github.com-atom-node-keytar-releases-download-v4.2.1-keytar-v4.2.1-node-v48-linux-x64.tar.gz
prebuild-install info unpack resolved to /usr/lib/node_modules/wey/node_modules/keytar/build/Release/keytar.node
prebuild-install info unpack required /usr/lib/node_modules/wey/node_modules/keytar/build/Release/keytar.node successfully
prebuild-install info install Successfully installed prebuilt binary!

> wey@0.1.0 install /usr/lib/node_modules/wey
> node scripts/install.js

/usr/lib/node_modules/wey/scripts/install.js:10
async function downloadYode(version, platform, arch, cacheDir) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wey@0.1.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wey@0.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/will/.npm/_logs/2018-04-09T20_43_30_312Z-debug.log
```

**Comment by IDerr** [comment]
Hello :D 
 node: '6.14.1'
You need to have Node 8+ to use this project due to async/await

**Comment by wjdp** [comment]
Fab, thanks for pointing out :+1:

**Comment by j6s** [comment]
Currently 8 seems to be the only supported version - trying to set up a development environment with 9.5.0 yielded the same error as #1
