### ISSUE TITLE
gui.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorE

### ISSUE THREAD

**Issue by Mizuho32** [yue/wey#78]
## Synopsis
1.  `npm install -g wey` or clone the repository.
2.  `$ wey` or `$ ./scripts/start.js`
3.  I got below

```fish
$🐡 ./scripts/start.js
internal/modules/cjs/loader.js:718
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /media/voyager/home/mizuho/sources/wey/node_modules/gui/gui.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorE
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/media/voyager/home/mizuho/sources/wey/node_modules/gui/index.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

## Notes
This happens after 4c5e41e1005bf3a54b1583db6ab8f7001e80dc9c and so, I can launch the app before 4d18133257f755dd584204508d5b4aeb2aa499f4 but the app immediately got frozen.

## Environment
- OS: Manjaro(Arch Linux) and Ubuntu 16.04
- Node:  Node v8.11.4 (asdf-vm) and Node v8.10.0 (nvm)

**Comment by zcbenz** [comment]
The last version requires Node v10 to run locally, I'm merging this to #1 since they are essentially the same problem.

**Comment by Mizuho32** [comment]
Thank you, I could launch the app with Node v10.10.0 so README's description (Currently only Node.js 8.x is supported for running from source code) is Node.js 10.x right?

**Comment by zcbenz** [comment]
Yeah, I'll update README.
